# Generated by Django 4.2.7 on 2025-11-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_unseen_approved_post',
            field=models.BooleanField(default=False),
        ),
    ]
