# Generated by Django 4.2.7 on 2025-11-15 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название сервера')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('mod', models.CharField(max_length=50, verbose_name='Мод игры')),
                ('slots', models.IntegerField(verbose_name='Количество слотов')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='Порт')),
                ('plan', models.CharField(default='basic', max_length=50, verbose_name='Тариф')),
                ('gameap_server_id', models.IntegerField(blank=True, null=True, verbose_name='ID сервера в GameAP')),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Начальная цена')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Текущая цена')),
                ('status', models.CharField(choices=[('active', 'Активный аукцион'), ('sold', 'Продан'), ('cancelled', 'Отменён'), ('expired', 'Истёк срок')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала аукциона')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания аукциона')),
                ('sold_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата продажи')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_auction_servers', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_servers', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Аукцион сервера',
                'verbose_name_plural': 'Аукционы серверов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Создан'), ('bid_placed', 'Сделана ставка'), ('price_updated', 'Цена обновлена'), ('sold', 'Продан'), ('cancelled', 'Отменён'), ('expired', 'Истёк срок')], max_length=20, verbose_name='Действие')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время действия')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='auction.auctionserver', verbose_name='Аукцион')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История аукциона',
                'verbose_name_plural': 'Истории аукционов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма ставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время ставки')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auction.auctionserver', verbose_name='Аукцион')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_bids', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Ставка',
                'verbose_name_plural': 'Ставки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['auction', '-created_at'], name='auction_auc_auction_25c24a_idx')],
            },
        ),
    ]
