# Generated by Django 4.2.7 on 2025-11-15 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_servercase_total_limit'),
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionserver',
            name='user_server',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='servers.userserver', verbose_name='Сервер пользователя'),
        ),
    ]
