# Generated by Django 4.2.7 on 2025-11-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_postedit_options_remove_category_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_html',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='HTML контент'),
        ),
    ]
