# Generated by Django 4.2.7 on 2025-11-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_post_content_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumRewardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_character', models.DecimalField(decimal_places=4, default=0.01, max_digits=10, verbose_name='Цена за символ (₽)')),
                ('min_post_length', models.IntegerField(default=10, verbose_name='Минимальная длина поста (символов)')),
                ('max_daily_reward', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Максимальное дневное вознаграждение (опционально)')),
                ('enabled', models.BooleanField(default=True, verbose_name='Включить вознаграждения')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройка вознаграждений форума',
                'verbose_name_plural': 'Настройки вознаграждений форума',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='reward_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Вознаграждение получено'),
        ),
    ]
