# Generated by Django 4.2.7 on 2025-11-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_forumrewardconfig_post_reward_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отклонения'),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pending', 'На одобрении'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
