# Generated by Django 4.2.7 on 2025-11-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос/Ключевое слово')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('category', models.CharField(choices=[('about', 'О компании'), ('services', 'Услуги'), ('products', 'Продукты'), ('contacts', 'Контакты'), ('general', 'Общая информация')], default='general', max_length=20, verbose_name='Категория')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('priority', models.IntegerField(default=1, verbose_name='Приоритет (1-10)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'База знаний',
                'verbose_name_plural': 'База знаний',
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
