# Generated by Django 4.2.7 on 2025-11-15 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_knowledgebase'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restricted_write', models.BooleanField(default=False, help_text='Если True — пользователь не может писать')),
                ('restrict_forum_reply', models.BooleanField(default=False, help_text='Отключить возможность оставлять ответы в форуме')),
                ('restrict_server_view', models.BooleanField(default=False, help_text='Отключить просмотр вкладки сервера')),
                ('purchasable', models.BooleanField(default=False, help_text='Можно ли выкупить право писать')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_restrictions', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_restriction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ограничение чата',
                'verbose_name_plural': 'Ограничения чата',
            },
        ),
        migrations.CreateModel(
            name='ChatAdminMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_admin_messages', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сообщение администрации',
                'verbose_name_plural': 'Сообщения администрации',
                'ordering': ['-created_at'],
            },
        ),
    ]
