# Generated by Django 4.2.7 on 2025-11-15 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_supportticket_ticketreply'),
        ('chat', '0004_supportticket_ticketreply_and_more'),
    ]

    operations = [
    ]
