# Generated by Django 4.2.7 on 2025-11-16 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_merge_20251115_0851'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='chat_suppor_status_9931b2_idx',
            old_name='chat_support_status_c8d3e2_idx',
        ),
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='chat_suppor_user_id_c6fabb_idx',
            old_name='chat_support_user_id_a4f2b1_idx',
        ),
    ]
